# config/config.yaml

notification:
  mode: "webhook"
  
  webhook:
    url: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=56c79598-1731-4892-949b-c8becbf6b93d"
    
    # 需要 @ 的手机号 (可选，留空则不艾特)
    mention_list: [] 

schedules:
  times: ["10:00", "12:00", "15:30"]

holdings:
  - name: "纳斯达克100"
    symbol_ref: "usNDX"        # 纳指实盘指数

  - name: "沪深300指数"
    symbol_ref: "sh000300"  

  - name: "恒生科技指数"
    symbol_ref: "hkHSTECH"

  - name: "红利低波50"
    symbol_ref: "sh515450"     # 南方标普红利低波50ETF (场内实时)
